---
title: "Question 4"
documentclass: elsarticle
Thesis_FP: no
output:
  pdf_document:
    keep_tex: yes
    template: Tex/TexDefault.txt
    fig_width: null
    fig_height: 3.5
  html_document:
    df_print: paged
Author1: Ronan Morris
Ref1: Stellenbosch University
Email1: 22876634
BottomRFooter: \footnotesize Page \thepage
addtoprule: yes
addfootrule: yes
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: yes
linenumbers: no
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: yes
toc: no
numbersections: yes
fontsize: 11pt
linestretch: 1.2
link-citations: yes
AddTitle: yes
---

# Past and Future Performance 

```{r setup, include=FALSE}

rm(list = ls())

tinytex::install_tinytex(force = TRUE)
options(repos = "https://cran.mirror.ac.za/")

gc() 

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

if(!require("tidyverse")) install.packages("tidyverse")

library(tidyverse)

```

```{r Setting Up}

rm(list = ls())

Rets <- read_rds("data/ASISA_Rets.rds") %>%
  mutate(Fund = str_trim(Fund)) 

Flows <- read_rds("data/ASISA_Flows.rds") %>%
  mutate(Fund = str_trim(Fund)) %>%
  filter(Fund %in% unique(Rets$Fund)) 

# I only want funds that have existed over the entire time period. 

Data <- left_join(Flows, Rets, by = c("date", "Fund", "Index", "FoF")) %>% 
    na.omit() %>% 
    filter(Index == "No") %>% 
    group_by(Fund) %>%
    filter(min(date) == as.Date("2003-10-31") & 
             max(date) == as.Date("2023-09-30")) %>%
    ungroup()

```

```{r Winners}

library(dplyr)
library(ggplot2)

source("Question 5/code/WinnersComparison.R")

# Get unique dates from the original dataset.

unique_dates <- sort(unique(Data$date))

# Apply the function to generate plot data for each date range.

plot_data_list <- lapply(1:(length(unique_dates)-2), function(i) {
  start_date <- unique_dates[i]
  end_date <- unique_dates[i + 1]
  next_date <- unique_dates[i + 2]
  
  # Call the function and generate the plot data.
  
  WinnersComparison((Data %>% filter(Index == "No")), start_date, end_date, next_date)
})

# Combine the plot data into a single data frame.

combined_plot_data <- do.call(rbind, plot_data_list)

# Create a density plot using ggplot for the combined data.

g1 <-
ggplot(combined_plot_data, aes(x = Returns, fill = Variable)) +
  geom_density(alpha = 0.6) +
  labs(title = "Distribution of Winners and Subsequent Performance",
       x = "",
       y = "") +
  scale_fill_manual(values = c("Winners" = "lightblue", 
                               "Subsequent" = "red4")) +
     xlim(c(-0.1, 0.16)) +
    guides(fill = guide_legend(title = "")) +
  theme_bw()

```

```{r Losers}

source("Question 5/code/LosersComparison.R")

# Repeat the Process. 

unique_dates <- sort(unique(Data$date))

plot_data_list <- lapply(1:(length(unique_dates)-2), function(i) {
  start_date <- unique_dates[i]
  end_date <- unique_dates[i + 1]
  next_date <- unique_dates[i + 2]
  
  # Call the function and generate the plot data.
  
  LosersComparison((Data %>% filter(Index == "No")), start_date, end_date, next_date)
})

# Repeat the process. 

combined_plot_data <- do.call(rbind, plot_data_list)

# Create a density plot using ggplot for the combined data.

g2 <-
ggplot(combined_plot_data, aes(x = Returns, fill = Variable)) +
  geom_density(alpha = 0.6) +
  labs(title = "Distribution of Losers and Subsequent Performance",
       x = "",
       y = "") +
  scale_fill_manual(values = c("Losers" = "red4", 
                               "Subsequent" = "lightblue")) +
     xlim(c(-0.15, 0.15)) +
    guides(fill = guide_legend(title = "")) +
  theme_bw()

```

```{r ,  warning =  FALSE, fig.align = 'center', fig.cap = " \\label{Figure4.1}", fig.ext = 'png', fig.height = 3, fig.width = 6}

g1

```

```{r ,  warning =  FALSE, fig.align = 'center', fig.cap = " \\label{Figure4.2}", fig.ext = 'png', fig.height = 3, fig.width = 6}

g2

```

# Flows and Past Returns 

```{r Starting Again}

library(tidyverse)
library(zoo)

rm(list = ls())

Rets <- read_rds("data/ASISA_Rets.rds") %>%
  mutate(Fund = str_trim(Fund)) 

Flows <- read_rds("data/ASISA_Flows.rds") %>%
  mutate(Fund = str_trim(Fund)) %>%
  filter(Fund %in% unique(Rets$Fund)) 

# I only want funds that have existed over the entire time period. 

Data <- left_join(Flows, Rets, by = c("date", "Fund", "Index", "FoF")) %>% 
    na.omit() %>% 
    filter(Index == "No") %>% # active managers
    group_by(Fund) %>%
    filter(min(date) == as.Date("2003-10-31") & 
             max(date) == as.Date("2023-09-30")) %>%
    ungroup()

```

```{r Correlation}

###

DataAverage <- Data %>%
  arrange(Fund, date) %>%
  group_by(Fund) %>%
  mutate(AvgReturnsPast3Years = zoo::rollapply(Returns, width = 36, FUN = mean, align = "right", partial = TRUE)) %>%
  ungroup() %>%
  na.omit() %>% 
    mutate(Flows = Flows/10000)

###

(DataAverage %>% 
    filter(AvgReturnsPast3Years < median(AvgReturnsPast3Years), 
           Flows > 0) %>% 
    nrow(.))/nrow(DataAverage)*100

###

ggplot(DataAverage, aes(x = AvgReturnsPast3Years, y = Flows)) +
    geom_smooth(method = "lm", se = TRUE, color = "grey") +
    annotate("rect", 
             xmin = -Inf, 
             xmax = median(DataAverage$AvgReturnsPast3Years), 
             ymin = -Inf, 
             ymax = median(DataAverage$Flows), 
             fill = "red", 
             alpha = 0.18) +
    annotate("rect", 
             xmin = median(DataAverage$AvgReturnsPast3Years), 
             xmax = Inf, 
             ymin = -Inf, 
             ymax = median(DataAverage$Flows), 
             fill = "lightblue", 
             alpha = 0.2) +
    annotate("rect", 
             xmin = -Inf,
             xmax = median(DataAverage$AvgReturnsPast3Years), 
             ymin = median(DataAverage$Flows), 
             ymax = Inf,
             fill = "pink", 
             alpha = 0.2) +
    annotate("rect", 
             xmin = median(DataAverage$AvgReturnsPast3Years),
             xmax = Inf, 
             ymin = median(DataAverage$Flows), 
             ymax = Inf, 
             fill = "blue", 
             alpha = 0.18) +
  labs(title = "Correlation Between Flows and Returns",
       x = "Average Returns (3yr)",
       y = "Flows") +
    geom_label(aes(x = -0.025, 
                   y = 12500, 
                   label = "19.9%"), 
               fill = "white", 
               color = "black") +
    geom_label(aes(x = 0.1, 
                   y = 12500, 
                   label = "25.54%"), 
               fill = "white", 
               color = "black") +
    geom_label(aes(x = -0.025,
                   y = -5000, 
                   label = "30.1%"), 
               fill = "white", 
               color = "black") +
  geom_label(aes(x = 0.1, 
                 y = -5000, 
                 label = "24.46%"), 
             fill = "white", 
             color = "black") +
  theme_bw()

```

```{r ,  warning =  FALSE, fig.align = 'center', fig.cap = " \\label{Figure4.3}", fig.ext = 'png', fig.height = 3, fig.width = 6}

ggplot(DataAverage, aes(x = AvgReturnsPast3Years, y = Flows)) +
    geom_smooth(method = "lm", se = TRUE, color = "grey") +
    annotate("rect", 
             xmin = -Inf, 
             xmax = median(DataAverage$AvgReturnsPast3Years), 
             ymin = -Inf, 
             ymax = median(DataAverage$Flows), 
             fill = "red", 
             alpha = 0.18) +
    annotate("rect", 
             xmin = median(DataAverage$AvgReturnsPast3Years), 
             xmax = Inf, 
             ymin = -Inf, 
             ymax = median(DataAverage$Flows), 
             fill = "lightblue", 
             alpha = 0.2) +
    annotate("rect", 
             xmin = -Inf,
             xmax = median(DataAverage$AvgReturnsPast3Years), 
             ymin = median(DataAverage$Flows), 
             ymax = Inf,
             fill = "pink", 
             alpha = 0.2) +
    annotate("rect", 
             xmin = median(DataAverage$AvgReturnsPast3Years),
             xmax = Inf, 
             ymin = median(DataAverage$Flows), 
             ymax = Inf, 
             fill = "blue", 
             alpha = 0.18) +
  labs(title = "Correlation Between Flows and Returns",
       x = "Average Returns (3yr)",
       y = "Flows") +
    geom_label(aes(x = -0.025, 
                   y = 12500, 
                   label = "19.9%"), 
               fill = "white", 
               color = "black") +
    geom_label(aes(x = 0.1, 
                   y = 12500, 
                   label = "25.54%"), 
               fill = "white", 
               color = "black") +
    geom_label(aes(x = -0.025,
                   y = -5000, 
                   label = "30.1%"), 
               fill = "white", 
               color = "black") +
  geom_label(aes(x = 0.1, 
                 y = -5000, 
                 label = "24.46%"), 
             fill = "white", 
             color = "black") +
  theme_bw()

```


