---
title: "Question 2"
documentclass: elsarticle
Thesis_FP: no
output:
  pdf_document:
    keep_tex: yes
    template: Tex/TexDefault.txt
    fig_width: null
    fig_height: 3.5
  html_document:
    df_print: paged
Author1: Ronan Morris
Ref1: Stellenbosch University
Email1: 22876634
BottomRFooter: \footnotesize Page \thepage
addtoprule: yes
addfootrule: yes
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: yes
linenumbers: no
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: yes
toc: no
numbersections: yes
fontsize: 11pt
linestretch: 1.2
link-citations: yes
AddTitle: yes
---
```{r setup, include=FALSE}

rm(list = ls())

tinytex::install_tinytex(force = TRUE)
options(repos = "https://cran.mirror.ac.za/")

gc() 

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

if(!require("tidyverse")) install.packages("tidyverse")

library(tidyverse)

library(rportfolios)

```

```{r}

rm(list = ls())

Indexes <- read_rds("data/Cncy_Hedge_Assets.rds")

# ALBI is bonds (local)
# J433 is equities (local)
# bbg agg is Bloomberg bond aggregator. (foreign)
# msci acwi is equities. (foreign)

ZAR <- read_rds("data/Monthly_zar.rds") %>% 
    filter(date >= as.Date(
        first(
            Indexes$date))) %>%
    select(-Tickers)

### How much should I hold in this portfolio given that I need a 60/40 split between equity/bonds and a 70/30 split between local/global split?

# for ALBI: 0.4 * 0.7 = 0.28
# for J433: 0.6 * 0.7 = 0.42
# for BBG: 0.4 * 0.3 = 0.12
# for MSCI: 0.6 * 0.3 = 0.18

# This sums to one. 

Weights <- c(0.18, 0.12, 0.42, 0.28)

Weights_Indexed <- Weights * (Indexes %>% select(-date))

Weights_Indexed$date <- Indexes$date

Weights_Indexed <- Weights_Indexed %>% slice(-1)

###

# Add a portfolio return column:

Weights_Indexed <- Weights_Indexed %>% 
    mutate(PortRet = rowSums(Weights_Indexed %>% select(-date)))

ZAR <- ZAR %>% 
    mutate(ZarRet = value/lag(value) - 1) %>% 
    slice(-1)

###

RetData <- as.data.frame( cbind(Weights_Indexed$PortRet, ZAR$ZarRet)) %>% 
    rename(PortRet = V1) %>% 
    rename(ZARRet = V2) %>% 
    na.omit(.)

```

```{r}

# Some calculations of %
# I continually changed the directions of these greater than signs. 

(RetData %>% 
    filter(PortRet > 0, ZARRet < 0) %>% 
    nrow(.))/nrow(RetData)*100

# 20.16% top right 
# 9.31% bottom left corner 
# 26.36% bottom right.
# 43.79% top left. 

```

```{r ,  warning =  FALSE, fig.align = 'center', fig.cap = " \\label{Figure2.1}", fig.ext = 'png', fig.height = 3, fig.width = 6}

ggplot(RetData, 
       aes(x = ZARRet, y = PortRet)) +
    annotate("rect", 
             xmin = -Inf, 
             xmax = 0, 
             ymin = -Inf, 
             ymax = 0, 
             fill = "red", 
             alpha = 0.18) +
    annotate("rect", 
             xmin = 0, 
             xmax = Inf, 
             ymin = -Inf, 
             ymax = 0, 
             fill = "lightblue", 
             alpha = 0.2) +
    annotate("rect", 
             xmin = -Inf,
             xmax = 0, 
             ymin = 0, 
             ymax = Inf,
             fill = "pink", 
             alpha = 0.2) +
    annotate("rect", 
             xmin = 0,
             xmax = Inf, 
             ymin = 0, 
             ymax = Inf, 
             fill = "blue", 
             alpha = 0.18) +
    geom_point(color = "steelblue4", 
               alpha = 0.45) +
    geom_smooth(method = "lm", 
                se = TRUE, 
                color = "grey") + 
  labs(title = "Scatter Plot of Return Correlation",
       x = "Portfolio",
       y = "ZAR/USD") +
    geom_vline(xintercept = -0.025, 
               linetype = "dotted", 
               color = "black", 
               alpha = 0.5, 
               size = 1) +
    xlim(c(-0.2, 0.2)) +  
    ylim(c(-0.2, 0.2)) +
    geom_label(aes(x = -0.1, 
                   y = 0.1, 
                   label = "43.79%"), 
               fill = "white", 
               color = "black") +
    geom_label(aes(x = 0.1, 
                   y = 0.1, 
                   label = "20.16%"), 
               fill = "white", 
               color = "black") +
    geom_label(aes(x = -0.1,
                   y = -0.1, 
                   label = "9.31%"), 
               fill = "white", 
               color = "black") +
  geom_label(aes(x = 0.1, 
                 y = -0.1, 
                 label = "26.36"), 
             fill = "white", 
             color = "black") +
  theme_bw()

```

```{r ,  warning =  FALSE, fig.align = 'center', fig.cap = " \\label{Figure2.2}", fig.ext = 'png', fig.height = 3, fig.width = 6}

ggplot(RetData, 
       aes(x = ZARRet, 
           fill = "ZAR/USD")) +
  geom_density(alpha = 0.5) +
  geom_density(aes(x = PortRet, 
                   fill = "Portfolio"), 
                   alpha = 0.5) +
  labs(title = "Distribution of Returns",
       x = "",
       y = "") +
  scale_fill_manual(name = "",
                    values = c("ZAR/USD" = "green",
                               "Portfolio" = "blue")) +
  theme(legend.position = "bottom")

```

# Volatility

```{r}

rm(list = ls())

Indexes <- read_rds("data/Cncy_Hedge_Assets.rds") 

ZAR <- read_rds("data/Monthly_zar.rds") %>% 
    filter(date >= as.Date(first(Indexes$date))) %>%
    select(-Tickers)

Weights <- c(0.18, 0.12, 0.42, 0.28)

library(PerformanceAnalytics)
library(RcppRoll)
library(tbl2xts)

### Plain ole re balancing portfolio.

RebalancedData <- Return.portfolio(
    Indexes, weights = Weights, rebalance_on = "quarters") %>% 
    xts_tbl(.) %>% 
    mutate(RollSD = RcppRoll::roll_sd(1 + portfolio.returns, 
                                      36, 
                                      fill = NA, 
                                      align = "right") * sqrt(12)) %>%  
                                      filter(!is.na(RollSD))

### Portfolio Including Rand

ZAR <- ZAR %>% 
    mutate(ZarRet = value/lag(value) - 1) %>% 
    filter(date >= "2005-01-31") 

RandRebalance <- RebalancedData %>% 
    mutate(Hedged = (0.9*portfolio.returns + 0.1*ZAR$ZarRet))

# I assume this is incredibly dubious, but I could not figure out another way to argue that I am holding a portfolio that re balances every quarter, and holds 10% of the rand, so I did this weighted average. 

RandRebalance <- RandRebalance %>% 
    mutate(RollSDHedged = RcppRoll::roll_sd(1 + Hedged, 
                                      36, 
                                      fill = NA, 
                                      align = "right") * sqrt(12)) %>%  
                                      filter(!is.na(RollSDHedged)) %>% 
    select(date, 
           RollSD,
           RollSDHedged) 

###

library(fmxdat)

g <- RandRebalance %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = RollSD, color = "Excluding Rand"), size = 1) +
  geom_line(aes(y = RollSDHedged, color = "Including Rand"), size = 1) +
  labs(title = "Rolling Volatility",
       x = "Date",
       y = "Standard Deviation") +
  scale_color_manual(values = c("Excluding Rand" = "red", "Including Rand" = "red4")) +
    theme_fmx(title.size = ggpts(30),
              CustomCaption = F) + 
    
fmx_cols()

```

```{r ,  warning =  FALSE, fig.align = 'center', fig.cap = " \\label{Figure2.3}", fig.ext = 'png', fig.height = 3, fig.width = 6}

finplot(g, x.date.dist = "1 year", x.date.type = "%Y", x.vert = T, 
    y.pct = T, y.pct_acc = 1)

```

